### ISSUE TITLE
sub_home日本語名称(sub_home.name)がDB上で文字化け

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/SeichiAssist#101]
**どこか**の文字コードの問題と思われる。
ちなみに英語名称は問題ない。

**Comment by unchama** [comment]
DBの環境定義に`--character-set-server=utf8`を指定することで解決した。

以下は参考までに
```
# 開発用にDB+phpmyadmin環境を構築するdocker-compose定義ファイル

version: '3.3'

networks:
  seichiassist-develop:
    external: false

services:

  # phpmyadminのコンテナ
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - TZ=Asia/Tokyo
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    restart: always
    networks:
      - seichiassist-develop
    ports:
      # ホストアドレス:8080 でアクセス可能とする
      - "8080:80"
    depends_on:
      - db

  # dbのコンテナ
  db:
    image: mariadb:10.1.38-bionic
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=password
    # wait_timeout=60->28800 (TimeOut対策)
    # character-set-server=latin1->utf8 (文字化け対策)
    command: [
      '--wait_timeout=28800',
      '--character-set-server=utf8',
    ]
    networks:
      - seichiassist-develop
    volumes:
      # 初期投入データの場所を指定
      - ./initdb/:/docker-entrypoint-initdb.d
      # Mysql保存データを永続化
      - ./mysql:/var/lib/mysql
```
